use_frameworks!

platform :ios, '11.0'

target 'AnimatedLaunchScreenKit_Example' do
  pod 'AnimatedLaunchScreenKit', :path => '../'

  target 'AnimatedLaunchScreenKit_Tests' do
    inherit! :search_paths

    
  end
end
